# VHS file (https://github.com/charmbracelet/vhs)

Output demo.gif

Set FontSize 32
Set Width 1200
Set Height 600


Show
Type "git clone https://github.com/tolik518/GBA_Pong"  Sleep 300ms Enter
Sleep 2 s

Type "cd GB" Tab@500ms Sleep 300ms Enter

Type "make buil" Tab@500ms Sleep 1.5s Enter
Sleep 5s

Type "make com"  Tab@500ms Sleep 800ms Enter
Sleep 3s

Type "ls -1 out" Sleep 800ms Enter
Sleep 5s
